[package]
name = "hns-resolver"
description = "Locally DNSSEC-validated HNS service and TLSA resolution"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hns-dns-wire = { path = "../hns-dns-wire" }
hns-dnssec = { path = "../hns-dnssec" }
thiserror = "2.0.19"

[dev-dependencies]
openssl = "0.10.81"

[lints]
workspace = true
